sudo: false

language: python

python: 
  - '3.6'

install: 
- pip3 install -U pip
- pip3 install -r requirements.txt
- pip3 install pytest
- pip3 install pytest-cov
- pip3 install coveralls


script: 
- sphinx-build -Wv docs/source docs/build/html

- coverage run stdm/tests/test_primes.py
- coverage run stdm/tests/test_plugin.py
- coverage combine
- coverage report -m

after_success: 
  - coveralls

deploy: 
  github_token: $STDM_TOKEN
  local_dir: docs/build/html
  notifications: 
    email: 
      on_failure: always
      on_success: always
      recipients: 
        - kngeno.kevin@gmail.com
  provider: pages
  skip_cleanup: true
  true: 
    branch: master
    tags: true

