services: 
    - docker
    
env:
    global:
        - IMAGE=qgis/qgis
        - QGIS_VERSION_TAG=final-3_4_4
        - PLUGIN_NAME=stdm
    
before_install:
    - docker-compose up -d
    - docker-compose ps
    - sleep 10
    - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"

script:
    - docker-compose exec qgis-testing-environment sh -c "cd /tests_directory"
    - docker version
    - docker-compose version
    - docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
    
branches:
  only:
    - master

email:
  - gkahiu@gmail.com