sudo: false
services: 
  - docker
    
addons:
  apt:
    packages:
      - docker-ce
    
env:
  global:
    - QGIS_IMAGE=qgis/qgis
    - QGIS_VERSION_TAG=final-3_4_4
    - PLUGIN_NAME=stdm
    - PG_IMAGE=gkahiu/docker-postgis-stdm
    - PG_VERSION_TAG=10
    - DOCKER_QGIS_TEST_DIR=tests_directory

language: python

python: 
  - '3.6'

before_install:
- docker version
- docker-compose version
- docker-compose up -d
- docker-compose ps
- sleep 10
- docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker-compose exec qgis-testing-environment sh -c "pip3 install -r /${DOCKER_QGIS_TEST_DIR}/requirements.txt"

install: 
- pip3 install -U pip
- pip3 install -r requirements.txt
- pip3 install pytest
- pip3 install pytest-cov
- pip3 install coveralls


script:
- docker-compose exec qgis-testing-environment sh -c "cd /${DOCKER_QGIS_TEST_DIR}"
# - docker-compose exec qgis-testing-environment sh -c "black --check stdm" # failed - no stdm directory
- docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
- sphinx-build -Wv docs/source docs/build/html
# coverage
- coverage run stdm/tests/test_plugin.py
# create coverage report
- coverage report -m
# zip files
- tar czpvf stdm-${TRAVIS_TAG:-dev}.tar.gz stdm
- zip -9 -r stdm-${TRAVIS_TAG:-dev}.zip stdm
- ls -l stdm-*.tar.gz stdm-*.zip

after_success: 
  - coveralls
  # "curl -T index.html -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_ADDRESS/master/"
  # "curl -T index.html -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_ADDRESS/tags/"

before_deploy:
  # set up git user name and tag this commit
  # - git config --local user.name "kngeno"
  # - git config --local user.email "kngeno.kevin@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:  
  - provider: pages
    github_token: $STDM_TOKEN
    local_dir: docs/build/html
    
    skip_cleanup: true
    on: 
      branch: master
      tags: true
  - provider: releases
    user: $USER
    password: $PASSWORD
    file:
      - stdm-*.tar.gz
      - stdm-*.zip
    file_glob: true
    skip_cleanup: true
    on:
      tags: true

after_deploy:
- ls -l stdm-*.tar.gz

notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients: 
      - kngeno.kevin@gmail.com