language: python
branches:
  only:
  - master
python:
  - '3.6'

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - sphinx-build -Wv docs/source docs/build/html
  - py.test
  #- coverage run --source=stdm/ -m py.test
  - pytest --cov=stdm/hello/
  - coverage report -m
  - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  # test the docs

  # send coverage report to coveralls
  - coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $STDM_TOKEN # set in the travis dashboard
  local_dir: docs/build/html
  on:
    branch: master
  notifications:
    email:
      recipients:
        - kngeno.kevin@gmail.com
      on_success: always
      on_failure: always