sudo: false
services: 
  - docker
    
addons:
  apt:
    packages:
      - docker-ce
    
env:
  global:
    - QGIS_IMAGE=qgis/qgis
    - QGIS_VERSION_TAG=final-3_4_4
    - PLUGIN_NAME=stdm
    - PG_IMAGE=gkahiu/docker-postgis-stdm
    - PG_VERSION_TAG=10
    - DOCKER_QGIS_TEST_DIR=tests_directory


language: python

python: 
  - '3.6'

before_install:
  - docker version
  - docker-compose version
  - docker-compose up -d
  - docker-compose ps
  - sleep 10
  - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
  - docker-compose exec qgis-testing-environment sh -c "pip3 install -r /${DOCKER_QGIS_TEST_DIR}/requirements.txt"

install: 
  # 
  - pip3 install -U pip
  - pip3 install -r requirements.txt



script:
- docker-compose exec qgis-testing-environment sh -c "cd /${DOCKER_QGIS_TEST_DIR}"
# - docker-compose exec qgis-testing-environment sh -c "black --check stdm" # failed - no stdm directory
- docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
# 
# coverage
- coverage run stdm/tests/test_plugin.py
# create coverage report
- coverage report -m
# 


after_success:
  #
  - coveralls
  # sphinx api docs build
  # sphinx user manual build
  - sphinx-build -Wv docs/source docs/build/html
  - sphinx-build -b html docs/source/ docs/build/

before_deploy:
  - chmod +x -R scripts/
  - ls -l stdm-*.tar.gz stdm-*.zip

deploy:  
  - provider: pages
    github_token: $STDM_TOKEN
    local_dir: docs/build/html
    skip_cleanup: true
    keep_history: true
    on: 
      branch: master

  - provider: script
    script: bash scripts/deploy_master.sh
    skip_cleanup: true
    on:
      branch: master
  
  - provider: script
    script: bash scripts/deploy_tags.sh
    skip_cleanup: true
    on:
      tags: true
      branch: master
      
  - provider: releases
    user: $USER
    password: $PASSWORD
    file:
      - stdm-*.tar.gz
      - stdm-*.zip
    
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      branch: master

after_deploy:
  - ls -l stdm-*.tar.gz stdm-*.zip

notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients: 
      - kngeno.kevin@gmail.com
