services: 
    - docker
    
addons:
  apt:
    packages:
      - docker-ce
    
env:
    global:
        - QGIS_IMAGE=qgis/qgis
        - QGIS_VERSION_TAG=final-3_4_4
        - PLUGIN_NAME=stdm
        - PG_IMAGE=gkahiu/docker-postgis-stdm
        - PG_VERSION_TAG=10
        - DOCKER_QGIS_TEST_DIR=tests_directory
    
before_install:
    - docker version
    - docker-compose version
    - docker-compose up -d
    - docker-compose ps
    - sleep 10
    - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
    - docker-compose exec qgis-testing-environment sh -c "pip3 install /${DOCKER_QGIS_TEST_DIR}/requirements.txt"

script:
    - docker-compose exec qgis-testing-environment sh -c "cd /${DOCKER_QGIS_TEST_DIR}"
    - docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
    
branches:
  only:
    - master

email:
  - gkahiu@gmail.comg