sudo: false

language: python

python: 
  - "3.6"

install: 
- "pip install -U pip"
- "pip install -r requirements.txt"
- "pip install pytest"
- "pip install pytest-cov"
- "pip install coveralls"


script: 
- "sphinx-build -Wv docs/source docs/build/html"
- "py.test --cov=stdm/hello/test_meter.py"


after_success: 
  - coveralls

deploy: 
  github_token: $STDM_TOKEN
  local_dir: docs/build/html
  notifications: 
    email: 
      on_failure: always
      on_success: always
      recipients: 
        - kngeno.kevin@gmail.com
  provider: pages
  skip_cleanup: true
  true: 
    branch: master
    tags: true

