services: 
    - docker
    
env:
    - IMAGE=qgis/qgis
    - QGIS_VERSION_TAG=final-3_4_4
    - PLUGIN_NAME=stdm
    
before_install:
    # Pull from QGIS docker repository
    - docker pull ${IMAGE}:${QGIS_VERSION_TAG}
    
install:
    - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 ${IMAGE}:{QGIS_VERSION_TAG}
    - sleep 10 # This is required to allow xvfb to start
    # Setup qgis and enables the plugin
    - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
    # Fix the symlink created by qgis_setup.sh
    - docker exec  -it qgis-testing-environment sh -c "rm -f  /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/${PLUGIN_NAME}"
    - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/ /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/${PLUGIN_NAME}"

script:
    - docker exec -it qgis-testing-environment sh -c "cd /tests_directory && qgis_testrunner.sh tests.test_Plugin"
    
branches:
  only:
    - master

email:
  - gkahiu@gmail.com