sudo: required

services: 
    - docker
    
addons:
  apt:
    packages:
      - docker-ce
    
env:
    global:
        - DOCKER_VERSION=1.13.1-0~ubuntu-trusty
        - DOCKER_COMPOSE_VERSION=1.23.2
        - QGIS_IMAGE=qgis/qgis
        - QGIS_VERSION_TAG=final-3_4_4
        - PLUGIN_NAME=stdm
        - PG_IMAGE=mdillon/postgis
        - PG_VERSION_TAG=10
    
before_install:
    - docker version
    - docker-compose version
    - docker-compose up -d
    - docker-compose ps
    - sleep 10
    - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"

script:
    - docker-compose exec qgis-testing-environment sh -c "cd /tests_directory"
    - docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
    
branches:
  only:
    - master

email:
  - gkahiu@gmail.com