language: python
branches:
  only:
  - master
python:
- '3.6'

install:
- pip install -U pip
- pip install -r requirements.txt
script:
cd docs/
- make html
after_success:
  #test the docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token # set in the Travis dashboard
  local_dir: docs/build/html
  on:
    branch: master
  notifications:
    email:
      recipients:
        - kngeno.kevin@gmail.com # your email here
      on_success: never
      on_failure: always