sudo: false
language: python
branches:
    only:
    - master
python:
  - '3.6'

branches:
  only:
    - master

services: 
    - docker
    
addons:
  apt:
    packages:
      - docker-ce
    
env:
    global:
        - QGIS_IMAGE=qgis/qgis
        - QGIS_VERSION_TAG=final-3_4_4
        - PLUGIN_NAME=stdm
        - PG_IMAGE=gkahiu/docker-postgis-stdm
        - PG_VERSION_TAG=10
        - DOCKER_QGIS_TEST_DIR=tests_directory

before_install:
    - docker version
    - docker-compose version
    - docker-compose up -d
    - docker-compose ps
    - sleep 10
    - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
    - docker-compose exec qgis-testing-environment sh -c "pip3 install -r /${DOCKER_QGIS_TEST_DIR}/requirements.txt"

install:
  - pip3 install -U pip
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install coveralls

before_script:

script:
  - sphinx-build -Wv docs/source docs/build/html
  - docker-compose exec qgis-testing-environment sh -c "cd /${DOCKER_QGIS_TEST_DIR}"
  - docker-compose exec qgis-testing-environment sh -c "black --check stdm"
  - docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
  - py.test --cov
  "check coverage tests and reports"
after_success:
  - coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $STDM_TOKEN
  local_dir: docs/build/html
  on:
    tags: true
    branch: master
  notifications:
    email:
      recipients:
        - kngeno.kevin@gmail.com
      on_success: always
      on_failure: always