sudo: required

services: 
    - docker
    
env:
    global:
        - DOCKER_VERSION=1.13.1-0~ubuntu-trusty
        - DOCKER_COMPOSE_VERSION=1.23.2
        - QGIS_IMAGE=qgis/qgis
        - QGIS_VERSION_TAG=final-3_4_4
        - PLUGIN_NAME=stdm
        - PG_IMAGE=mdillon/postgis
        - PG_VERSION_TAG=10
    
before_install:
    - echo "deb https://packages.docker.com/1.13/apt/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
    - sudo apt-get update && sudo apt-get upgrade docker-engine
    - sudo rm -f /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker version
    - docker-compose version
    - docker-compose up -d
    - docker-compose ps
    - sleep 10
    - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"

script:
    - docker-compose exec qgis-testing-environment sh -c "cd /tests_directory"
    - docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
    
branches:
  only:
    - master

email:
  - gkahiu@gmail.com