language: python
branches:
  only:
  - master
python:
  - '3.6'

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - sphinx-build -Wv docs/source docs/build/html
  #- py.test --doctest-modules --cov . # commented to pass
  #- py.test --cov-report term-missing --cov=maths
  #- py.test --doctest-modules --cov=maths3 --cov-report term-missing
  #- py.test
  - py.test --cov
  #- coverage report -m
  #- nosetests --with-coverage # Add me to run nose with coverage support.
  "check coverage tests and reports"
after_success:
  # test the docs

  # send coverage report to coveralls
  - coveralls

# sphinx github pages io
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $STDM_TOKEN # set in the travis dashboard
  local_dir: docs/build/html
  on:
    tags: true
    branch: master
  notifications:
    email:
      recipients:
        - kngeno.kevin@gmail.com
        #- gkahiu@gmail.com
      on_success: always
      on_failure: always

email:
    #- gkahiu@gmail.com
    - kngeno.kevin@gmail.com

notifications:
  email:
    recipients:
      #- gkahiu@gmail.com
      - kngeno.kevin@gmail.com