version: '3.4'

x-common-env-vars:
    &common-env
    POSTGRES_PASSWORD: 'stdmtest'
    PGHOST: stdm-db
    PGPORT: 5432
    PGDATABASE: stdm
    PGUSER: postgres
    PGPASSWORD: stdmtest

services:
  stdm-db:
    image: ${PG_IMAGE}:${PG_VERSION_TAG}
    restart: always
    environment: *common-env
    volumes:
        - ./docker/:/${DOCKER_USER_DIR}
    
  qgis-testing-environment:
    image: ${QGIS_IMAGE}:${QGIS_VERSION_TAG}
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./:/${DOCKER_QGIS_TEST_DIR}
    environment:
        << : *common-env
        DISPLAY: ':99'
        QT_X11_NO_MITSHM: '1'
    links:
        - stdm-db
    