version: '3.4'

x-common-env-vars:
    &common-env
    POSTGRES_PASSWORD: 'stdmtest'
    PGHOST: stdm-db
    PGPORT: 5432
    PGDATABASE: stdm
    PGUSER: postgres
    PGPASSWORD: stdmtest

services:
  stdm-db:
    image: ${PG_IMAGE}:${PG_VERSION_TAG}
    restart: always
    environment: *common-env
    volumes:
        - ./docker_config/db_init.sh:/db_init.sh
    