version: '3'

services:
  qgis-testing-environment:
    image: ${IMAGE}:{QGIS_VERSION_TAG}
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./:/tests_directory
    environment:
        DISPLAY: ':99'
        QT_X11_NO_MITSHM: '1'