version: '3.4'

x-common-env-vars:
    &common-env
    PGPORT: 5432
    PGDATABASE: postgres
    PGUSER: postgres
    PGPASSWORD: postgres

services:
  stdm-db:
    image: ${PG_IMAGE}:${PG_VERSION_TAG}
    restart: always
    environment: *common-env
    
