version: '3.4'

x-common-env-vars:
    &common-env
    POSTGRES_PASSWORD: 'stdmtest'
    POSTGRES_DB: 'stdm'

services:
  stdm-db:
    image: ${PG_IMAGE}:${PG_VERSION_TAG}
    environment: *common-env
    
  qgis-testing-environment:
    image: ${QGIS_IMAGE}:${QGIS_VERSION_TAG}
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./:/tests_directory
    environment:
        << : *common-env
        DISPLAY: ':99'
        QT_X11_NO_MITSHM: '1'
    links:
        - stdm-db
    